number1 = int(input("enter the first number: "))
number2 = int(input("enter the second number: "))
print(number1 + number2)
number3 = int(input("enter the first number: "))
number4 = int(input("enter the second number: "))
print(number3 + number4)
number5 = int(input("enter the first number: "))
number6 = int(input("enter the second number: "))
print(number5 + number6)
